[김장호] 상품 상세페이지 - GET view 작성
wecode-bootcamp-korea/24-1st-MANNAMCHU-backend pull request #5
Opened 2021-09-03 05:47 UTC by flow2lime

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상품 상세페이지 GET 뷰 작성
		 
## 수정 사항들 자세한 내용
- url 에서 상품의 pk 인 'product-id' 를 참조
- 해당 상품의 이름, 가격, 옵션, 추가가격 등 모든 데이터를 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 기능만이 구현된 상태입니다. 예외처리에 관해서는 추후에 더 고민해보고 적용하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [해당없음] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [해당없음] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-03 06:06 UTC, S2-J1NG requested changes

2021-09-03 06:06 UTC, ghost commented on products/urls.py
> +    path('/', DetailView.as_view()),
url만 보고는 어떤 제품의 상세페이지를 조회하는 로직인지 판단하기 어렵습니다. 
restful api의 `path paramater`와 `query parameter` 중 어떤 것이 더 적절할 지 고민하고 적용해주세요!

2021-09-03 06:06 UTC, ghost commented on products/views.py
> +from django.shortcuts import render
사용하지 않는 내용은 삭제해주세요!

2021-09-03 06:06 UTC, S2-J1NG commented on products/views.py
> +            return image_set
list comprehension 찾아보시고 적용 해보세요~! 속도 개선과 코드를 깔끔하게 작성 할 수 있습니다.

2021-09-03 06:06 UTC, S2-J1NG commented on products/views.py
> +            return option_set
여기도 list comprehension 적용해보세요!

2021-09-03 06:07 UTC, S2-J1NG commented
발생할 수 있는 에러도 추가해주세요~!

2021-09-03 09:00 UTC, flow2lime commented
[Mod:~] for loop 를 리스트 컴프리핸션 적용 및 코드 정리를 반영했습니다. 확인 부탁드립니다.

2021-09-04 01:44 UTC, S2-J1NG requested changes

2021-09-04 01:44 UTC, ghost commented on products/views.py
> +            product_detail = Product.objects.get(id=product_id)
`product_detail`보다 `product`라는 변수가 더 적절해보입니다.
`product_detail` 이라는 변수는 description 내용이 포함되었을 때 사용하는 것이 더 좋습니다.

2021-09-04 01:44 UTC, S2-J1NG commented on products/views.py
> +                'options'     : getting_options(),
`getting_options()` 함수를 호출하는 것보다 여기서 바로 `product_id`를 기준으로 `options` 테이블로 바로 접근해서 해당 상품에 관한 이미지를 모두 가져올 수 있지 않을까요?
(hint ✨) `options` 테이블에는 `product_id`가 있습니다!

2021-09-04 01:44 UTC, S2-J1NG commented on products/views.py
> +                'image'       : getting_images(),
여기도 바로 product_id를 기준으로 image 테이블로 바로 접근해서 해당 상품에 관한 이미지를 모두 가져올 수 있지 않을까요?

2021-09-04 01:44 UTC, S2-J1NG commented on products/views.py
> +            return JsonResponse({'message': 'PAGE_NOT_FOUND'}, status=404)
상품이 없는 경우에 대한 에러 처리 잘 하셨습니다.
여기서 `Object` 로 나오는 값은 product 이기 때문에 아래와 같이 에러 처리 할 수도 있습니다.
예외 처리를 할 때는 상세하게 하는 것이 좋습니다

```
except Product.DoesNotExist:
            return JsonResponse({'message':'PRODUCT NOT EXIST'}, status=404)
```

2021-09-04 01:46 UTC, S2-J1NG commented
장호님, conflict 해결 해주세요!
`getting_images`와 `getting_options` 함수없이 queryset api로 충분히 구현할 수 있습니다!
테이블 관계 생각해서 수정해주세요!

2021-09-06 04:37 UTC, flow2lime commented
[Mod:~] 태그로 수정사항 반영해서 올려두었습니다. 
기존의 getting- 형식의 함수들을 try 구문 내부의 list comporehension 으로 바꿔두었습니다.
오류 메세지는 제안해주신 직관적인 문구로 교체했습니다.

2021-09-06 08:17 UTC, S2-J1NG commented
장호님~! product url.py 확인 해주세요!

2021-09-06 10:52 UTC, flow2lime commented
[Mod: organized urls.py] 커밋으로 올려두었습니다. 
urls.py 파일 두 개를 정리했습니다.
확인 부탁드립니다.

2021-09-07 00:42 UTC, S2-J1NG commented
수고하셨습니다 장호님!

2021-09-07 00:42 UTC, merged