[최현수] 상품 전체 리스트 및 필터링 view.py get 작성
wecode-bootcamp-korea/24-1st-MANNAMCHU-backend pull request #6
Opened 2021-09-03 09:04 UTC by filola

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- product 앱에서 view.py에 전체 리스트와 필터 출력을 작성
- 또 그와 연결을 위한 urls.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 필터링 부분에서 조건문으로 필터링을 주었는데 처음에 products를 all()로 가져오는 방법말고 필터링을 거는 방법이 있을까요?⭐️

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-04 02:03 UTC, S2-J1NG requested changes

2021-09-04 02:03 UTC, ghost commented on products/views.py
> +                    'image'      : list(product.image_set.filter(product_id=product.id).values('url')),
product_id를 알 수 있다면 `products` 테이블에서 역참조로 이미지를 찾는 게 아니라 `images` 테이블에서 정참조로 이미지를 url만 가져올 수 있지 않을까요?

2021-09-04 02:03 UTC, ghost commented on products/views.py
> +                })
list comprehension 공부하고 적용해보세요!

2021-09-04 02:03 UTC, ghost commented on products/views.py
> +from django.core.paginator import Paginator
`paginator` 모듈 외에 `offset-limit` 으로 구현할 수 있습니다. 어렵지 않으니 찾아서 적용해보세요!

2021-09-04 02:03 UTC, S2-J1NG commented on products/views.py
> +            products = Product.objects.all().order_by('id')
`id` 가 1번인 상품은 최근에 등록된 상품인가요? 보통 기본 정렬은 최근 등록된 순으로 합니다. 
다른 정렬 기준으로 할 수 있는지 고민해주세요!

2021-09-04 02:05 UTC, S2-J1NG commented
현수님 conflict 해결해주세요!
`tags` 테이블 수정한다고 하셔서 new, sale, best 부분은 보지 않았습니다. 변경된 테이블에 맞게 로직 작성해서 올려주세요~!
로직 작성 후 꼭 httpie나 포스트맨으로 통신한 결과까지 첨부해주세요

2021-09-05 14:37 UTC, filola commented on products/views.py
> +                    'image'      : list(product.image_set.filter(product_id=product.id).values('url')),
정참조로 수정했습니다!

2021-09-05 14:37 UTC, filola commented on products/views.py
> +                })
리스트 컴프리헨션으로 적용하고 태그부분 migration 새로 진행한 것으로 코드 다시 짰습니다.

2021-09-05 14:38 UTC, filola commented on products/views.py
> +            products = Product.objects.all().order_by('id')
역순으로 정렬 변경하였습니다!

2021-09-06 06:42 UTC, filola commented on products/views.py
> +from django.core.paginator import Paginator
변경하였습니다!

2021-09-06 06:42 UTC, filola commented
추가적으로 엔드포인트를 나눠 필터를 주던 부분들을 조건문과 tag를 받아와 입력에 따라 출력되는 값이 다르게 적용하였습니다

2021-09-06 06:45 UTC, filola commented
![스크린샷 2021-09-06 오후 3 45 04](https://user-images.githubusercontent.com/45662443/132172277-14191e8a-a7c0-4ef6-9cb3-f810c3379976.png)
![스크린샷 2021-09-06 오후 3 45 17](https://user-images.githubusercontent.com/45662443/132172290-7196da33-e539-4317-98f6-c5eeef4b26dd.png)

2021-09-06 08:39 UTC, S2-J1NG requested changes

2021-09-06 08:39 UTC, S2-J1NG commented on products/views.py
> +                    'discount'   : list(ProductTag.objects.filter(product_id=product.id, tag_id=sale.id).values('sale_rate')), # 문제 :
`get` 을 이용하면 `discount`라는 key로 충분히 전달 할 수 있지 않을까요?
조건이 여러 개여도 반환되는 값이 1개이면 `get` 을 사용할 수 있습니다.

2021-09-06 08:39 UTC, S2-J1NG commented on products/views.py
> +                    'image'      : list(Image.objects.filter(product_id=product.id).values('url')),
list comprehension 형태로 만들어보세요!

2021-09-06 08:39 UTC, S2-J1NG commented on products/views.py
> +                    'tag'        : list(product.tags.values('name')),
여기도 list comprehension 형태로 만들 수 있습니다.

2021-09-06 08:44 UTC, S2-J1NG requested changes

2021-09-06 08:44 UTC, S2-J1NG commented on products/views.py
> +                products = Product.objects.filter(tags=best.id).order_by('-id') [offset:limit]
`qeury parameter`를 사용하면 filter 한 번으로 해결 가능합니다.
restful API를 이용하여 수정해주세요

2021-09-06 12:10 UTC, filola commented on products/views.py
> +                    'image'      : list(Image.objects.filter(product_id=product.id).values('url')),
변경하였습니다!

2021-09-06 12:10 UTC, filola commented on products/views.py
> +                    'tag'        : list(product.tags.values('name')),
변경하였습니다!

2021-09-06 12:10 UTC, filola commented on products/views.py
> +                products = Product.objects.filter(tags=best.id).order_by('-id') [offset:limit]
qeury parameter적용하였습니다.

2021-09-06 12:11 UTC, filola commented on products/views.py
> +                    'discount'   : list(ProductTag.objects.filter(product_id=product.id, tag_id=sale.id).values('sale_rate')), # 문제 :
filter안에 product가 리스트 컴프리헨션으로 적용되는 변수여서 밖으로 뺼수가 없었습니다. 리스트 컴프리헨션 형태로 전환만 하였습니다.

2021-09-07 00:44 UTC, S2-J1NG commented
현수님 불필요한 주석 삭제 해주세요!
conflict 해결해주시고 통신 결과 첨부 해주세요~!

2021-09-07 01:42 UTC, filola commented
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 514 bytes | 514.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/wecode-bootcamp-korea/24-1st-MANNAMCHU-backend.git
   97a06e5..d27f4de  feature/product-list -> feature/product-list
Branch 'feature/product-list' set up to track remote branch 'feature/product-list' from 'origin'.

2021-09-07 03:54 UTC, filola commented
`{
    "products": [
        {
            "name": "chicken",
            "price": "10000.00",
            "discount": [],
            "image": [
                "eeee",
                "eeeee"
            ],
            "tag": [
                "best",
                "new"
            ],
            "like_count": 30
        },
        {
            "name": "coffee",
            "price": "6000.00",
            "discount": [
                0
            ],
            "image": [
                "ddd",
                "dddd",
                "eee"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "noodles",
            "price": "4000.00",
            "discount": [
                10
            ],
            "image": [
                "ccc",
                "cccc"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "ramen",
            "price": "5000.00",
            "discount": [
                10
            ],
            "image": [
                "bbb",
                "bbbb"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "kimchi",
            "price": "3000.00",
            "discount": [],
            "image": [
                "aaaa",
                "aaaaa"
            ],
            "tag": [
                "new"
            ],
            "like_count": 30
        }
    ],
    "page": 1
}`

2021-09-07 03:54 UTC, filola commented
`{
    "products": [
        {
            "name": "chicken",
            "price": "10000.00",
            "discount": [],
            "image": [
                "eeee",
                "eeeee"
            ],
            "tag": [
                "best",
                "new"
            ],
            "like_count": 30
        },
        {
            "name": "coffee",
            "price": "6000.00",
            "discount": [
                0
            ],
            "image": [
                "ddd",
                "dddd",
                "eee"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "noodles",
            "price": "4000.00",
            "discount": [
                10
            ],
            "image": [
                "ccc",
                "cccc"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "ramen",
            "price": "5000.00",
            "discount": [
                10
            ],
            "image": [
                "bbb",
                "bbbb"
            ],
            "tag": [
                "best",
                "new",
                "sale"
            ],
            "like_count": 30
        },
        {
            "name": "kimchi",
            "price": "3000.00",
            "discount": [],
            "image": [
                "aaaa",
                "aaaaa"
            ],
            "tag": [
                "new"
            ],
            "like_count": 30
        }
    ],
    "page": 1
}`

2021-09-07 06:36 UTC, S2-J1NG commented
수고하셨습니다 현수님!

2021-09-07 06:36 UTC, merged