[김장호] 장바구니 POST & DELETE 뷰 작성
wecode-bootcamp-korea/24-1st-MANNAMCHU-backend pull request #8
Opened 2021-09-07 07:44 UTC by flow2lime

## 수정 사항 간략한 한줄 요약
- 카트 POST & DELETE  뷰 작성
		 
## 수정 사항들 자세한 내용
- POST : 
    - 유저 및 옵션 유효성 검사
    - 카트에 아이템 추가
    - 카트 안에 이미 존재하는 상품은 수량만 증가
- DELETE : 
    - 카트에 존재하는 아이템 삭제
    - 없는 아이템 삭제 시도 필터링

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [해당없음] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [해당없음] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-07 08:10 UTC, S2-J1NG requested changes

2021-09-07 08:10 UTC, S2-J1NG commented on products/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
이 부분은 로그인 데코레이터로 처리 할 수 있습니다!

2021-09-07 08:10 UTC, S2-J1NG commented on products/views.py
> +            return JsonResponse({'message': 'ADDED_ITEM_INTO_YOUR_CART'}, status=201)
`update_or_create` 을 이용하면 코드를 줄일 수 있습니다.
찾아서 공부하고 적용해보세요!

2021-09-07 08:10 UTC, S2-J1NG commented
conflict 해결해주세요!

2021-09-08 05:26 UTC, flow2lime commented
[Mod:~] 태그로 수정사항 올려두었습니다.
- update_or_create 메서드를 사용해서 카트 POST 를 재구성했습니다.
- 로그인 데코레이터를 적용했습니다.

2021-09-08 06:37 UTC, S2-J1NG requested changes

2021-09-08 06:37 UTC, S2-J1NG commented on products/views.py
> +                        )
if문에서 cart가 있다면 수량 업데이트 처리가 되어 있는데 else문에서 update를 처리해줘야 하는 이유가 있을까요?

2021-09-08 06:37 UTC, S2-J1NG commented
장호님 리뷰 확인해주세요!

2021-09-08 07:18 UTC, flow2lime commented on products/views.py
> +                        )
update_or_create 메서드를 사용할 때, quantity 도 고유값으로 계산이 되기 때문에 넣어두었습니다.
예를 들어 if-else 구문을 사용하지 않을 경우,
한 유저가 감자 2kg, 3개를 이미 장바구니에 넣어둔 상태에서 추가로 감자 2kg, 7개를 장바구니에 넣을 경우에 수량만 갱신되지않고 새로운 데이터 row 가 생기는 상황이었습니다.

혹시 제가 조사를 좀 부족하게 한 건 아닐까 싶네요 하하...

2021-09-08 08:43 UTC, S2-J1NG commented on products/views.py
> +                        )
cart, created = Cart.objects.update_or_create() 으로 다시 찾아보시면 해결할 수 있을거예요!
장고 공식 문서 다시 읽으면 해결 할 수 있을거예요~!
https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update-or-create

2021-09-08 08:43 UTC, S2-J1NG commented
conflict 해결 해주세요!

2021-09-08 10:33 UTC, S2-J1NG commented
수고하셨습니다 장호님~

2021-09-08 10:33 UTC, merged