[최현수] Cart GET&PATCH
wecode-bootcamp-korea/24-1st-MANNAMCHU-backend pull request #9
Opened 2021-09-07 08:42 UTC by filola

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- products 앱의 view.py 내부에 cart에 관한 GET&PATCH작성 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-07 08:55 UTC, S2-J1NG requested changes

2021-09-07 08:55 UTC, S2-J1NG commented on products/views.py
> +
발생할 수 있는 에러 찾아서 처리 해주세요~!

2021-09-07 11:09 UTC, filola commented on products/views.py
> +
데이터가 없을때의 예외 몇개 잡았습니다.

2021-09-08 01:26 UTC, S2-J1NG commented
어제 말씀 드린 내용 참고해서 장호님과 상의 후 `patch` 내용 제외 여부 알려주세요!
포스트맨 통신 결과 첨부 해주세요

2021-09-08 02:45 UTC, filola commented
{
    "message": [
        {
            "product": "kimchi",
            "price": "3000.00",
            "option_id": 1,
            "option": "aaa",
            "addtional_price": "1000.00",
            "quantity": 1,
            "image": "aaaa",
            "sale_rate": []
        },
        {
            "product": "kimchi",
            "price": "3000.00",
            "option_id": 2,
            "option": "aaaa",
            "addtional_price": "1000.00",
            "quantity": 9,
            "image": "aaaa",
            "sale_rate": []
        },
        {
            "product": "ramen",
            "price": "5000.00",
            "option_id": 3,
            "option": "bbb",
            "addtional_price": "1000.00",
            "quantity": 9,
            "image": "bbb",
            "sale_rate": [
                10
            ]
        },
        {
            "product": "ramen",
            "price": "5000.00",
            "option_id": 3,
            "option": "bbb",
            "addtional_price": "1000.00",
            "quantity": 10,
            "image": "bbb",
            "sale_rate": [
                10
            ]
        }
    ]
}

2021-09-08 06:38 UTC, S2-J1NG commented
현수님 수고하셨습니다~!

2021-09-08 06:38 UTC, merged